package `fun`.nightshift.launcher.backend.db

import org.jetbrains.exposed.dao.id.LongIdTable
import org.jetbrains.exposed.dao.id.UUIDTable
import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.ReferenceOption
import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.javatime.CurrentTimestamp
import org.jetbrains.exposed.sql.javatime.timestamp
import java.time.Instant
import java.util.UUID

/**
 * Exposed table definitions for the schema declared by V1__init_schema.sql.
 *
 * Notes:
 *  - All UUID primary keys are generated by `gen_random_uuid()` on the
 *    PostgreSQL side, so we never set the `id` column from Kotlin on insert.
 *  - JSONB and INET columns are exposed as text/varchar here for simplicity;
 *    richer typed wrappers can be added later if needed.
 */

/** `accounts` - registered launcher users. */
object Accounts : UUIDTable("accounts") {
    val login: Column<String> = varchar("login", 20).uniqueIndex("idx_accounts_login")
    val email: Column<String> = varchar("email", 255).uniqueIndex("idx_accounts_email")
    val passwordHash: Column<String> = text("password_hash")
    val hwid: Column<String> = varchar("hwid", 64)
    val hwidStatus: Column<String> = varchar("hwid_status", 20).default("locked")
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)
    val updatedAt: Column<Instant> = timestamp("updated_at").defaultExpression(CurrentTimestamp)
}

/** `sessions` - opaque session tokens issued at login/registration. */
object Sessions : UUIDTable("sessions") {
    val accountId = reference("account_id", Accounts, onDelete = ReferenceOption.CASCADE)
    val token: Column<String> = varchar("token", 64).uniqueIndex("idx_sessions_token")
    val hwid: Column<String> = varchar("hwid", 64)
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)
    val expiresAt: Column<Instant> = timestamp("expires_at")
    val isValid: Column<Boolean> = bool("is_valid").default(true)

    init {
        index("idx_sessions_account", isUnique = false, accountId)
    }
}

/** `activation_keys` - per-tier purchase/redeem keys. */
object ActivationKeys : UUIDTable("activation_keys") {
    val keyValue: Column<String> = varchar("key_value", 32).uniqueIndex("idx_activation_keys_value")
    val keyType: Column<String> = varchar("key_type", 10) // day | week | month | lifetime
    val accountId = reference("account_id", Accounts, onDelete = ReferenceOption.SET_NULL).nullable()
    val hwid: Column<String?> = varchar("hwid", 64).nullable()
    val activatedAt: Column<Instant?> = timestamp("activated_at").nullable()
    val expiresAt: Column<Instant?> = timestamp("expires_at").nullable()
    val status: Column<String> = varchar("status", 10).default("unused")
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)

    init {
        index("idx_activation_keys_account", isUnique = false, accountId)
    }
}

/** `login_attempts` - used by the rate limiter to count failed logins. */
object LoginAttempts : LongIdTable("login_attempts") {
    val login: Column<String> = varchar("login", 20)
    // INET is rendered as varchar at the Exposed level - PostgreSQL accepts string literals.
    val ipAddress: Column<String> = varchar("ip_address", 45)
    val attemptedAt: Column<Instant> = timestamp("attempted_at").defaultExpression(CurrentTimestamp)
    val success: Column<Boolean> = bool("success")

    init {
        index("idx_login_attempts_login_time", isUnique = false, login, attemptedAt)
    }
}

/** `password_reset_requests` - operator-driven password reset workflow. */
object PasswordResetRequests : UUIDTable("password_reset_requests") {
    val accountId = reference("account_id", Accounts, onDelete = ReferenceOption.CASCADE)
    val comment: Column<String?> = text("comment").nullable()
    val resetCode: Column<String?> = varchar("reset_code", 8).nullable()
    val codeExpiresAt: Column<Instant?> = timestamp("code_expires_at").nullable()
    val status: Column<String> = varchar("status", 20).default("pending")
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)
}

/** `online_heartbeats` - last seen timestamp per session, used by the online counter. */
object OnlineHeartbeats : Table("online_heartbeats") {
    val sessionId: Column<UUID> = uuid("session_id")
        .references(Sessions.id, onDelete = ReferenceOption.CASCADE)
    val lastSeen: Column<Instant> = timestamp("last_seen").defaultExpression(CurrentTimestamp)

    override val primaryKey = PrimaryKey(sessionId)
}

/** `telemetry_events` - opt-in product telemetry. */
object TelemetryEvents : LongIdTable("telemetry_events") {
    val sessionId: Column<UUID?> = uuid("session_id").nullable()
    val eventType: Column<String> = varchar("event_type", 50)
    // JSONB rendered as text - fine for inserts/selects via parameterised queries.
    val payload: Column<String?> = text("payload").nullable()
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)

    init {
        index("idx_telemetry_events_created", isUnique = false, createdAt)
    }
}

/** `crash_reports` - uncaught exception captures from the desktop client. */
object CrashReports : LongIdTable("crash_reports") {
    val sessionId: Column<UUID?> = uuid("session_id").nullable()
    val stackTrace: Column<String> = text("stack_trace")
    val clientVersion: Column<String?> = varchar("client_version", 20).nullable()
    val createdAt: Column<Instant> = timestamp("created_at").defaultExpression(CurrentTimestamp)
}
